### ISSUE TITLE
Save button in Edit Players tab not functioning

### ISSUE THREAD

**Issue by Dlorii** [chirpxiv/PalettePlus#1]
Hey chirp, first off I'm very excited for the first release! :3 

To the bug, it appears that the Save button currently doesn't function in the Edit Players tab.

My assumption is that a little window is supposed to open once clicked to type in a name for the palette.
Similar to how the + button works in the Saved Palettes tab, that one however does work and allowed me to save a palette.

**Comment by chirpxiv** [comment]
yeah that's my bad as I'd simply forgotten to implement it sorry, heading to sleep now but will try to get it fixed in the morning, ty for reporting it

**Comment by chirpxiv** [comment]
should hopefully be fixed now with the v0.1.1 release
