### ISSUE TITLE
Game crash in Eureka Orthos when transformed into Owlette

### ISSUE THREAD

**Issue by centizen** [chirpxiv/PalettePlus#13]
Hi there! 

Was running Eureka Orthos earlier with some friends when I triggered a Owl trap. This causes the player model to be transformed into an "Owlette" for 30 seconds. This caused my game to crash. 

It looks to me like the crash log is indicating PallettePlus as the cause. Apologies if this is not the case, but I figured I should put an issue up in case it's an unintended issue caused by the new Deep Dungeon. 

Thanks!

https://pastebin.com/mMhwGyyX

**Comment by chirpxiv** [comment]
This is caused by Mare Synchronos calling IPC functions in the wrong thread.

> at MareSynchronos.Managers.IpcManager.PalettePlusBuildPalette() in A:\src\client\MareSynchronos\Managers\IpcManager.cs:line 628
